server:
  port: 9898

rsa:
  public-key: classpath:certs/public.pem
  private-key: classpath:certs/private.pem

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sgtm-db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    baselineOnMigrate: true
    locations: classpath:db/migration/dev

gps-provider:
  name: gpswox
  base-url: https://app.aza-gps.ma/api
  email: anas@aza.ma
  password: iiVcVbe99t8j

synchronization:
  cron:
    devices: 0 0 1 * * *
    day-report: 0 5 0 * * *
