server:
  port: 9898

rsa:
  public-key: classpath:certs/public.pem
  private-key: classpath:certs/private.pem

spring:
  datasource:
    url: jdbc:postgresql://server.cloud.ma:5432/proxy
    username: spring_user
    password: sd#f3&63ka89!bp23
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    baselineOnMigrate: true
    locations: classpath:db/migration/prod

traccar:
  base-url: http://194.147.58.41:8082/api
  email: anas@aza.ma
  password: 123456789

gpswox:
  base-url: http://194.147.58.41:8082/api
  email: anas@aza.ma
  password: 123456789

synchronization:
  cron:
    devices: 0 0 1 * * *
    day-report: 0 5 0 * * *
